/* Deskpal visual frame revision contract. */
#ifndef DESKPAL_FRAME_REVISION_H
#define DESKPAL_FRAME_REVISION_H

#define DESKPAL_FRAME_REVISION_LEN 32
#define DESKPAL_FRAME_PROJECTION_MAX_DIMENSION 256
#define DESKPAL_FRAME_PROJECTION_MAX_BYTES \
	(DESKPAL_FRAME_PROJECTION_MAX_DIMENSION * \
	 DESKPAL_FRAME_PROJECTION_MAX_DIMENSION * 4)

#endif /* DESKPAL_FRAME_REVISION_H */
